# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7233c3a664495858adbb3406b7be4814aaad353b6381ff2b6bb47f9ec0db6be34983db08470851ec5e5e76bab1054fbe28e9b7ae4b76a99d22186059d4550648

test:
  secret_key_base: d4f13aebe327a701ba5d7c141aee6cea549eb2ee0f04acba6e6d3ca8cd84a107c32cfce41c506d64a2ef8b1a5594c05a167756c0ad31f41c8525a0527884c43f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
